server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: order-service-route
          uri: http://order-service.orders.svc.cluster.local:8080
          predicates:
            - Path=/api/order/**,/api/menu/**,/api/category/**,/api/option/**

        - id: inventory-service-route
          uri: http://inventory-service.inventory.svc.cluster.local:8080
          predicates:
            - Path=/api/inventory/**

        - id: user-service-route
          uri: http://user-service.user.svc.cluster.local:8080
          predicates:
            - Path=/api/user/**,/api/store/**,/api/email/**

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}