spring:
  datasource:
    url: ${ORDER_DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jackson:
    time-zone: Asia/Seoul
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true          # SQL 예쁘게 출력
        use_sql_comments: true
        dialect: org.hibernate.dialect.MariaDBDialect
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP}
      group-id: inventory-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.common.dto"